-- Up
CREATE TABLE groundhogs (
  id INTEGER PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  shortname TEXT,
  name TEXT,
  city TEXT,
  region TEXT,
  country TEXT,
  source TEXT,
  currentPrediction TEXT,
  isGroundhog BOOLEAN,
  type TEXT,
  active BOOLEAN,
  description TEXT
);

CREATE TABLE predictions (
  id INTEGER PRIMARY KEY,
  slug TEXT,
  year INTEGER,
  shadow BOOLEAN,
  details TEXT,
  FOREIGN KEY(slug) REFERENCES groundhogs(slug),
  UNIQUE (slug, year)
);

/* Insert Groundhogs */
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (1, 'punxsutawney-phil', 'Phil', 'Punxsutawney Phil', 'Punxsutawney', 'Pennsylvania', 'USA', 'https://www.groundhog.org/history-past-predictions', 'https://www.groundhog.org/prognostication', 1, 'Groundhog', '1', 'Punxsutawney Phil is a prognosticating groundhog from Pennsylvania. He makes his predictions from his burrow on Gobler’s Knob. According to legend, Phil has made weather prognostications since 1886, owing his improbably long life to the miraculous “groundhog nog” administered at the annual Groundhog Picnic.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (2, 'octoraro-orphie', 'Orphie', 'Octoraro Orphie', 'Quarryville', 'Pennsylvania', 'USA', 'http://home.ptd.net/\%7Emsvitale/index.html', 'https://lancasteronline.com/octoraro-orphies-2022-prognostication-at-the-slumbering-groundhog-lodge-photos/collection_bcba45f4-844a-11ec-9598-236672ff5898.html', 0, 'Taxidermied Groundhog', '1', 'Octoraro Orphie, from Quarryville Pennsylvania, is a world-renowned weather prognosticator and the One True Groundhog. Other so-called groundhogs draw more celebrity endorsements, but Orphie is not distracted by the worldly pursuits of fame and fortune (at least partially due to his being stuffed and mounted). He is a sharp dresser, often spotted in his dapper top hat and bow tie.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (3, 'wiarton-willie', 'Willie', 'Wiarton Willie', 'Wiarton', 'Ontario', 'Canada', 'https://www.southbrucepeninsula.com/en/explore-and-play/wiarton-willie.aspx#Past-predictions', 'https://www.southbrucepeninsula.com/en/explore-and-play/wiarton-willie.aspx#Prediction-morning-February-2nd', 1, 'Groundhog', '1', 'Wiarton Wille is Canada’s most famous prognosticating groundhog, from the town of Wiarton, Ontario. Every February 2nd, Willie announces his prediction in Groundhogese to The Mayor of the Land and of the Marmot, the only person who can speak Groundhogese.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (4, 'jimmy-the-groundhog', 'Jimmy', 'Jimmy the Groundhog', 'Sun Prarie', 'Wisconsin', 'USA', 'https://twitter.com/groundhogjimmy', 'https://www.marshfieldnewsherald.com/story/life/be-wisconsin/2022/02/02/groundhog-day-2022-sun-prairies-jimmy-delivers-his-prognostication/9254422002/', 1, 'Groundhog', '1', 'Jimmy the Groundhog is based in Sun Prairie, Wisconsin, the proclaimed “World Headquarters of the Groundhog,” whose annual emergence from the ground on February 2nd foretells the coming of spring.  Jimmy has an extremely high accuracy rate on his annual predictions, making him an outstanding leader in meteorological circles. He occasionally bites mayors’ ears.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (5, 'buckeye-chuck', 'Chuck', 'Buckeye Chuck', 'Marion', 'Ohio', 'USA', 'https://en.wikipedia.org/wiki/Buckeye_Chuck#Past_predictions', 'https://twitter.com/OHBuckeyeChuck/status/1488861276780392452', 1, 'Groundhog', '1', 'Buckeye Chuck is a weather-predicting groundhog in Marion, Ohio. In 1979, the Ohio legislature named Chuck the official groundhog for the Ohio state. Buckeye Chuck lives a comfortable, celebrity lifestyle — only working one day a year — but he doesn’t let the fame get to his head.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (6, 'general-beauregard-lee', 'Beau', 'General Beauregard Lee', 'Jackson', 'Georgia', 'USA', 'https://twitter.com/genbeaulee', 'https://twitter.com/genbeaulee/status/1488854634626174979', 1, 'Groundhog', '1', 'General Beauregard Lee is Georgia’s Official Weather Prognosticator, widely considered the principal prognosticator for the Southern United States. General Beau lives comfortably in his groundhog-sized mansion known as Weathering Heights, where he enjoys naps, digging tunnels, and hashbrowns.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (7, 'gertie-the-groundhog', 'Gertie', 'Gertie the Groundhog', 'Hanna City', 'Illinois', 'USA', 'https://www.facebook.com/watch/wildlifeprairiepark/', 'https://www.hoiabc.com/2022/02/02/gertie-groundhog-predicts-early-spring/', 1, 'Groundhog', '1', 'Gertie the Groundhog is a celebrated meteorologist from Wildlife Prairie State Park, Illinois. Since 1993, Gertie has been predicting the weather on February 2nd from her wildlife chalet, inspiring local musician Barry Cloyd to write the original, hit song “Wake-Up Gertie.”');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (8, 'lander-lil', 'Lil', 'Lander Lil', 'Lander', 'Wyoming', 'USA', 'https://www.facebook.com/BLMWyoming', 'https://cowboystatedaily.com/2022/02/02/bill-sniffin-lander-lil-predicts-early-spring-in-wyoming-we-hope/', 0, 'Statue of a prairie dog', '1', 'Lander Lil, a bronze statue of a prairie dog, has been predicting the future of winter weather for Wyoming since 1984. There really was a real Lander Lil before the installation of a larger-than-life bronze statue, which stands lookout from her perch on the grounds of the local Post Office.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (9, 'shubenacadie-sam', 'Sam', 'Shubenacadie Sam', 'Shubenacadie', 'Nova Scotia', 'Canada', 'https://data.novascotia.ca/Lands-Forests-and-Wildlife/Shubenacadie-Wildlife-Park-Groundhog-Day-Predictio/4y37-h2yu', 'https://twitter.com/ShubenacadieSam/status/1488845184418959360', 1, 'Groundhog', '1', 'Shubenacadie Sam is a weather-predicting groundhog who resides at the Shubenacadie Wildlife Park in Nova Scotia. Living on the eastern edge of Canada, Sam makes the first prediction in North America every year at 8:00 am AST. Sam is active on Twitter and enjoys yoga and meditation.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (10, 'staten-island-chuck', 'Chuck', 'Staten Island Chuck', 'New York City', 'New York', 'USA', 'https://en.wikipedia.org/wiki/Staten_Island_Chuck#Past_predictions', 'http://www.statenislandzoo.org/groundhog-day/', 1, 'Groundhog', '1', 'Staten Island Chuck — also known as Charles G. Hogg — is a groundhog living at the Staten Island Zoo in New York City. He is one of the most accurate groundhogs, with an 85\% accuracy rate. Chuck bit the hand of Mayor Michael Bloomberg and was subsequently the victim of an alleged manslaughter by succeeding Mayor Bill De Blasio.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (11, 'malverne-mel', 'Malverne Mel', 'Malverne Mel', 'Malverne', 'New York', 'USA', 'https://www.facebook.com/crossroadsfarmatgrossmanns', 'https://www.longislandpress.com/2022/02/02/holtsville-hal-malverne-mel-disagree-on-groundhog-day-prediction/', 1, 'Groundhog', '1', 'Groundhog Day with Malverne Mel is a tradition more than 2 decades old in Malverne, New York. Not happy with only predicting the weather, Mel is an art connoisseur and also hosts a poster contest. Mel is also a huge fan of the Bill Murray movie, “Groundhog Day.”');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (12, 'holtsville-hal', 'Hal', 'Holtsville Hal', 'Holtsville', 'New York', 'USA', 'https://www.facebook.com/brookhavenwildlifecenter', 'https://tbrnewsmedia.com/tag/holtsville-hal/', 1, 'Groundhog', '1', 'Holtsville Hal is the True Blue First Rate North American Groundhog for the proud Holtsville residents, whose prognostications are presented by Superintendent of Highways Daniel P. Losquadro. (The hot drink of the event is “HALuccino!) Hal’s introductory jingle goes: “Will he see it or will he not? Trust Holtzville Hal, he’s who we’ve got.”');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (13, 'two-rivers-tunnel', 'Tunnel', 'Two Rivers Tunnel', 'Cape Breton', 'Nova Scotia', 'Canada', 'https://www.facebook.com/TwoRiversWildlifePark/', 'https://www.saltwire.com/atlantic-canada/news/six-more-weeks-of-winter-cape-bretons-two-rivers-tunnel-makes-annual-groundhog-day-prediction-100688061/', 1, 'Groundhog', '1', 'Two Rivers Tunnel is the official prognosticator for Cape Breton, located in Two Rivers Wildlife Park. Tunnel the groundhog lives in a charming green house and speaks in a distinct Groundhogese dialect — most likely native to Cape Breton, where he has been making predictions for over 20 years.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (14, 'fred-la-marmotte', 'Fred', 'Fred la Marmotte', 'Val-d’Espoir', 'Quebec', 'Canada', 'https://www.fredlamarmotteofficielleduquebec.ca', 'https://globalnews.ca/news/8588505/quebec-fred-la-marmotte-groundhog-day-2022/', 1, 'Groundhog', '1', 'Fred la marmotte is a Canadian groundhog located in Val-d’Espoir in the Gaspésie, Quebec who predicts weather on Groundhog Day. Overwhelmed by his gift of clairvoyance, Fred relies upon his handler and a mascot in his likeness to announce his prediction. Fred is unique in being the only weather-predicting groundhog whose habitat is located on a World Heritage Site, the “Géoparc mondial UNESCO de Percé.”');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (15, 'snohomish-slew', 'Slew', 'Snohomish Slew', 'Snohomish', 'Washington', 'USA', 'https://www.facebook.com/Groundfrogday/', 'https://www.facebook.com/Groundfrogday/posts/pfbid0PD8qUbfsVFxHNJBm3WVVgLtyL71FUfHX88UxoQSGUdA5ZB38znWLUPzi2tfeWZ5Nl', 0, 'Bullfrog', '1', 'Snohomish Slew, a frognosticating bullfrog, makes an annual weather forecast for the Pacific Northwest in downtown Snohomish. There is much accompanying pomp and ceremony. From Thayer Cueter, Slew’s handler: “The pinnacle celebration moment [is] when Slew whispers his frogcast to his favourite scribe in Groundfrogese. [The] gathered crowd will be ribbeted! by every transcribed word from Slew as he accurately predicts our winter weather fate for six more weeks.”');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (16, 'woody-the-woodchuck', 'Woody', 'Woody the Woodchuck', 'Howell', 'Michigan', 'USA', 'https://www.facebook.com/howellnaturecenter', 'https://www.mlive.com/news/ann-arbor/2022/02/its-official-woody-the-groundhog-declares-six-more-weeks-of-winter.html', 1, 'Groundhog', '1', 'Woody the Woodchuck, Michigan’s official clairvoyant groundhog, has been prognosticating for over 2 decades. Unlike the ‘shadow’ technique used by most groundhogs, Woody’s forecast is determined by the time she spends outside on a ceremonial tree stump: 30 seconds or longer means an early spring, any less means a chilly six more weeks of winter.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (17, 'flatiron-freddy', 'Freddy', 'Flatiron Freddy', 'Boulder', 'Colorado', 'USA', 'https://twitter.com/boulderosmp', 'https://twitter.com/boulderosmp/status/1488908742565318657?lang=en', 0, 'Taxidermied yellow-bellied marmot', '1', 'Flatiron Freddy is a top hat-wearing, yellow-bellied marmot that became a Groundhog Day weather prognosticator about a decade ago. Freddy is stuffed — not with the secret wisdom of unforetold weather events, but with actual stuffing, having died some years ago. Freddy generally chooses to arrive in style: sometimes flying in via zipline, rolling up in a monster truck, or sliding in on his snowboard.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (18, 'bee-cave-bob', 'Bob', 'Bee Cave Bob', 'Bee Cave', 'Texas', 'USA', 'https://twitter.com/beecavebob', 'https://www.kxan.com/news/texas/texas-icon-bee-cave-bob-an-armadillo-predicts-an-early-spring/', 0, 'Armadillo', '1', 'Bee Cave Bob has helped Texans predict the early arrival of spring or the prolongment of winter since 2010. Bob is part of a Groundhog Day secessionist movement: with founder T. Booth rechristening it “Armadillo Day,” and stating “we don’t need no mangy groundhog in Pennsylvania predicting the weather for us.” In addition to weather forecasts, Bob also predicts the upcoming year’s partisan lean.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (19, 'chilly-charlie', 'Charlie', 'Chilly Charlie', 'Woodstock', 'Ontario', 'Canada', 'https://www.facebook.com/events/302076975234159', 'https://www.facebook.com/1047HeartFM/posts/4885586941490590', 0, 'Person in a groundhog suit', '1', 'Chilly Charlie is a groundhog mascot who makes the annual Groundhog Day prediction for Woodstock, Ontario. Woodstock’s traditional Groundhog Day celebration/pancake breakfast started in 2003, and has in recent years been modified to a drive-through format.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (20, 'beardsley-bart', 'Bart', 'Beardsley Bart', 'Bridgeport', 'Connecticut', 'USA', 'https://twitter.com/beardsleybart', 'https://www.beardsleyzoo.org/press/beardsley-bart-connecticuts-prognosticating-prairie-dog-makes-his-groundhog-day-weather-prediction', 0, 'Prairie dog', '1', 'Beardsley Bart is the principal prognosticating prairie dog from Connecticut’s Beardsley Zoo. His official title is Senior Spring Arrival Specialist. Every year, Beardsley Bart says that spring is coming eventually, and he has always been 100 percent correct.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (21, 'sand-mountain-sam', 'Sam', 'Sand Mountain Sam', 'Albertville', 'Alabama', 'USA', 'https://twitter.com/wqsb_1051/status/1488525058704384003', 'https://whnt.com/news/sand-mountain-sam-returns-and-predicts-an-early-spring/', 0, 'Opossum', '1', 'Sand Mountain Sam is a legendary prognosticating opossum from Albertville, Alabama, where he has been making predictions for over a decade. In 2020, the state game warden nearly cancelled the tradition (usually, having a possum as a pet is against the law), but in 2022 Sam returned, emerging from a whiskey barrel to predict an early spring.');
INSERT INTO groundhogs (id, slug, shortname, name, city, region, country, source, currentPrediction, isGroundhog, type, active, description) VALUES (22, 'stonewall-jackson', 'Stonewall', 'Stonewall Jackson', 'Wantage', 'New Jersey', 'USA', 'https://www.facebook.com/spacefarms', 'https://www.facebook.com/spacefarms/posts/pfbid0cRMSN3cTFLd41ynzM4efNeLQV4gdT2157ttbuZLckMRTWvcb3JVrxhQNG4ridfpjl', 1, 'Groundhog', '1', 'Stonewall Jackson (VI) is a weather-predicting groundhog from Wantage, New Jersey, where he lives on Space Farms. Stonewall is still “in training” but he is from a proud prognosticating dynasty so he should have a leg up on other would-be weather-guessers.');

/* Insert Predictions */
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2011, null, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2011, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2010, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2011, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2015, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2021, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1982, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1983, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1984, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1985, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1986, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1987, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1988, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1989, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1990, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1992, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1993, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1994, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1995, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1997, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1998, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 1999, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2000, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2001, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2003, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2004, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2005, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2007, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2010, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2011, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2012, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2015, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2016, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2007, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2009, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2010, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2011, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2015, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 1985, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 1986, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 1987, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 1994, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 1997, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 1999, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2000, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2005, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2006, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2007, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2009, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2021, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2016, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2017, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2021, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1915, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1926, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1929, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1931, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1932, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1933, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1934, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1935, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1936, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1937, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1938, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1939, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1940, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1941, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1942, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1943, null, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1944, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1945, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1946, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1947, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1948, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1949, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1950, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1951, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1952, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1953, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1954, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1955, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1956, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1957, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1958, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1959, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1960, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1961, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1962, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1963, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1964, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1965, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1966, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1967, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1968, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1969, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1970, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1971, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1972, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1973, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1974, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1975, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1977, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1978, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1979, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1980, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1981, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1982, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1983, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1984, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1985, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1986, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1987, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1988, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1989, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1990, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1991, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1992, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1993, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1995, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1996, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1997, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1998, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 1999, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2000, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2001, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2002, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2003, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2004, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2005, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2006, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2007, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2008, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2009, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2011, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2017, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2021, null, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1980, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1981, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1983, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1984, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1986, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1987, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1988, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1989, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1990, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1991, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1993, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1994, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1996, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1997, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1998, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 1999, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2000, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2001, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2002, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2003, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2004, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2005, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2006, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2007, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2009, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2016, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2017, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('beardsley-bart', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('bee-cave-bob', 2022, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('flatiron-freddy', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('general-beauregard-lee', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('fred-la-marmotte', 2022, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('holtsville-hal', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('lander-lil', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('chilly-charlie', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('octoraro-orphie', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('buckeye-chuck', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 1999, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2000, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2001, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2002, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2003, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2004, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2005, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2006, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2007, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2008, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2009, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2010, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2011, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2012, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2013, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2014, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2015, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2016, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2017, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2018, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2019, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2020, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2021, 0, 'No Shadow (Early Spring)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1886, null, 'Groundhog Day first recognized in Punxsutawney by Weathers Wags.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1887, 1, 'First Official trek to Gobbler’s Knob. Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1888, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1889, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1890, 0, 'No Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1891, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1892, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1893, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1894, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1895, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1896, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1897, null, 'No Record.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1898, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1899, null, 'No Record. Groundhog Club founded.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1900, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1901, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1902, 0, 'Probably No Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1903, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1904, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1905, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1906, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1907, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1908, 1, 'Saw Shadow; First front page coverage');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1909, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1910, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1911, 1, 'Saw Shadow; “55 couples at Groundhog Day Dance.”');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1912, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1913, 1, 'Saw Shadow at 8:80 am. First newspaper photo of Groundhog by John Frampton. A new dance “The Groundhog Roll” was demonstrated by Joe Winslow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1914, 1, 'Saw Shadow at 9:34 AM, Groundhog demonstrated “The Groundhog Flop”');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1915, 1, 'Saw Shadow at 11:45 AM');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1916, 1, 'Saw Shadow at 9:07; First films of the event. ');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1917, 1, 'Saw Shadow at 9:07.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1918, 1, 'Saw Shadow; Temperature 18 below zero.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1919, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1920, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1921, 1, 'Saw Shadow at 7:17 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1922, 1, 'Saw Shadow 7:11 AM; Groundhog Holiday Dance.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1923, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1924, 1, 'Saw Shadow 7:13 AM; First appearance of logo with groundhog with umbrella and newspaper.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1925, 1, 'Saw Shadow 8:13 AM; CJ Margiotti gave groundhog tradition to the Pittsburgh Travel Club.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1926, 1, 'Saw Shadow at 9:17 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1927, 1, 'Saw Shadow at 8:35 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1928, 1, 'Saw Shadow at 10 AM; Program with Punx’y Rotary Club was on KDKA Radio.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1929, 1, 'Predicted six more weeks of winter before sunrise.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1930, 1, 'Saw Shadow at 7:11 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1931, 1, 'Saw Shadow at 12:27 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1932, 1, 'Saw Shadow at 9:11 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1933, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1934, 0, 'No Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1935, 1, 'Saw Shadow at 9:11 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1936, 1, 'Saw Shadow at 10:27 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1937, 1, 'Saw Shadow at 9:09 AM; Unfortunate meeting with a skunk.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1938, 1, 'Saw Shadow at 9 AM; Blackest shadow in history.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1939, 1, 'Saw Shadow at 9:10 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1940, 1, 'Saw Shadow at 9 AM; Pictured with first Groundhog Day Queen, Miss Margaret Hunam.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1941, 1, 'Saw Shadow at 4:25 PM; Six Groundhog Girls.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1942, 1, 'Partial Shadow at 7:40 AM; “War clouds have blacked out parts of the shadow.” (“The Spirit,” Feb. 2, 1942).');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1943, 0, 'Groundhog didn’t make an appearance; relied on Quarryville’s prediction - NO Shadow');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1944, 1, 'Saw Shadow at 9:10 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1945, 1, 'Saw Shadow at 9 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1946, 1, 'Saw Shadow at 7:52 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1947, 1, 'Saw Shadow at 7:37 AM; First newspaper photo of Groundhog Club members at Gobbler’s Knob.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1948, 1, 'Saw Shadow at 8:46 AM; Dr. Frank Lorenzo was interviewed on KDKA Radio’s “Brunch With Bill” program.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1949, 1, 'Saw Shadow at 7:32 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1950, 0, 'No Shadow; Colleen Townsend, actress, was in town to promote the film, “When Willie Comes Marching Home.”');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1951, 1, 'Saw Shadow at 8:41 AM; Pictured with cheerleaders from PHS and SSCD. Betty Byers, Joan Wadding, Dorothy Armstrong and Kathleen Spinelli.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1952, 1, 'Saw Shadow at 7:52 AM; First appearance of Frau Gourndhog, Groundhog procession and shadow. Casting was on Dave Garroway’s TV Show on NBC on Monday, February 4.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1953, 1, 'Saw Shadow at 7:38 AM; First year with Sam Light as Groundhog Club president; First Man-of-the-Year Award goes to Ben Levy.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1954, 1, 'Saw Shadow at 8:03 AM; The groundhog was turned completely white from worry.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1955, 1, 'Saw Shadow at 8:51 AM; 4-inch snowfall on Groundhog Day; Coverage on three TV stations.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1956, 1, 'Saw Shadow 8:33 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1957, 1, 'Saw Shadow 7:47 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1958, 1, 'Saw Shadow at 8:27 AM; Prepared for blast-off in his “Chucknik” spacecraft; First Woman-of-the-Year Award was given to Mrs. Louis (Olive) Woodring.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1959, 1, 'Saw Shadow at 8:23 AM; Announces that he has returned from a successful trip to the moon.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1960, 1, 'Saw Shadow at 7:33 AM, forecasts extremely bad weather; appearance on the “Today” show.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1961, 1, 'Saw Shadow at 7:41 AM; 25 below zero.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1962, 1, 'Saw Shadow at 7:29 AM; Just returned from second trip to the moon.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1963, 1, 'Saw Shadow at 7:41 AM; Unusually dark shadow');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1964, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1965, 1, 'Saw Shadow shortly before 8 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1966, 1, 'Saw Shadow at 7:21 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1967, 1, 'Saw Shadow 7:25 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1968, 1, 'Saw Shadow 7:29 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1969, 1, 'Saw Shadow 7:29 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1970, 0, 'No Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1971, 1, 'Saw Shadow at 7:29 AM; 14 below zero.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1972, 1, 'Saw Shadow 7:30 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1973, 1, 'Saw Shadow 7:29 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1974, 1, 'Saw Shadow 8:28 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1975, 0, 'No Shadow; Declared at 7:31 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1976, 1, 'Saw Shadow at 7:29 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1977, 1, 'Saw Shadow at 7:27; In midst of energy crisis.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1978, 1, 'Saw Shadow at 7:28 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1979, 1, 'Saw Shadow at 7:28 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1980, 1, 'Saw Shadow at 7:29 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1981, 1, 'Saw Shadow at 7:27 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1982, 1, 'Saw Shadow 7:26 AM; After coldest January in more than a century.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1983, 0, 'No Shadow; Peered over at 7:29 AM, but saw no shadow; predicted an early spring after a mild winter.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1984, 1, 'Saw Shadow shortly after 7 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1985, 1, 'Saw Shadow at 7:28 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2007, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2009, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2010, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2012, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2015, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 1993, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 1994, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 1995, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 1996, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 1997, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 1998, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 1999, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2000, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2001, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2002, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2003, null, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2004, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2005, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2006, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2007, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2009, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2015, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2017, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2021, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2006, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2012, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2021, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1969, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1970, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1971, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1972, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1973, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1974, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1975, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1976, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1977, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1978, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1979, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1980, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1981, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1982, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1983, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1984, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1985, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1986, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1987, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1988, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1989, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1990, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1991, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1992, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1993, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1994, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1995, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1996, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1997, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1998, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 1999, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2000, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2001, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2002, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2003, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2004, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2005, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2006, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2007, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2009, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2017, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1982, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1984, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1985, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1987, null, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1988, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1993, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1994, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1995, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 1997, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2000, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2005, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2006, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2007, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2009, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2016, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2013, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2015, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2008, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2010, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2011, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2014, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2016, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2017, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2018, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2019, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2020, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2021, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1955, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1956, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1957, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1958, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1959, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1960, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1961, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1962, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1963, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1964, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1965, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1966, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1967, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1968, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1969, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1970, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1971, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1972, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1973, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1974, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1975, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1976, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1977, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1978, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1979, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1980, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1981, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1982, null, 'No record');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1983, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1984, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1985, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1986, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1987, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1988, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1989, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1990, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1991, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1992, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1993, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1994, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1995, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1996, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1997, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1998, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 1999, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2000, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2001, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2002, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2003, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2004, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2005, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2006, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2007, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2008, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2009, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2010, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2011, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2012, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2013, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2014, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2015, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2016, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2017, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2018, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2019, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2020, 1, 'Shadow, Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2021, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2002, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2010, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2011, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2012, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2013, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2014, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2015, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2016, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2017, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2018, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2019, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2020, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2021, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('shubenacadie-sam', 2022, 1, 'Shadow (Long Winter)');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('malverne-mel', 2022, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('gertie-the-groundhog', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('snohomish-slew', 2022, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('jimmy-the-groundhog', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('staten-island-chuck', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('sand-mountain-sam', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('stonewall-jackson', 2022, 0, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('woody-the-woodchuck', 2022, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('wiarton-willie', 2022, 0, 'No Shadow, Early Spring!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('two-rivers-tunnel', 2022, 1, '');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1986, 0, 'No Shadow! Visited President Reagan at the White House in March.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1987, 1, 'Saw Shadow 7:29 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1988, 0, 'No Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1989, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1990, 0, 'No Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1991, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1992, 1, 'Saw Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1993, 1, 'Saw Shadow. “Groundhog Day” The movie with Bill Murray was released in time for PHIL’S Predition.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1994, 1, 'Saw Shadow 7:28 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1995, 0, 'No Shadow; Guested on the Oprah Winfrey TV Show and made new fans.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1996, 1, 'Saw Shadow 7:21; So cold he dug deep to make his prediction.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1997, 0, 'No Shadow 7:25AM. Made his 110th prediction. Largest crowd the Knob has seen 35,000 people');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1998, 1, 'Saw Shadow 7:20AM; Six more weeks of “El Nino” Winter.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 1999, 0, 'Over 15,000 people celebrated as Phil saw no shadow at 7:23 AM and predicted and early spring');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2000, 1, 'It was the dawn of a new “Phillenium” and 12-degrees at Gobbler’s Knob when Phil saw his shadow at 7:28 AM.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2001, 1, 'Phil’s prediction of 6 more weeks of winter weather was displayed on the Astrovision in New York’s Time Square.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2002, 1, 'Phil saw his shadow at the largest event in 116 year history with estimated 30,000 people celebrating 02/02/02');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2003, 1, 'Phil saw his shadow at 7:25 AM as Pennsylvania’s newly elected Governor Ed Rendell looked on from Gobbler’s Knob.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2004, 1, 'Phil saw his shadow at 7:27 in 8 degree weather. Event was webcast live on www.groundhog.org');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2005, 1, 'The sky was clear as Phil saw his shadow before an enthusiastic crowd of 10-18,000. The time was 7:31 a.m. It was Phil’s 119th prediction.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2006, 1, 'Phil saw his shadow while wearing his Steeler “Terrible Towel” at 7:25 a.m. The temperature was a balmy 38 degrees.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2007, 0, 'No Shadow- Early Spring It was a cloudy morning with light snow flurries when Phil emerged from his burrow at about 7:26 a.m. and did not see his shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2008, 1, 'At 7:28 a.m., 29°, Phil Saw his Shadow.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2009, 1, 'At 7:26 a.m. Phil saw his shadow and Inner Circle President Bill Cooper completed his final interpretation and retired at Gobbler’s Knob.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2010, 1, 'The temperature was 12°. Saw Shadow- Six More Weeks of Winter');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2011, 0, 'No Shadow- Early Spring With rain over head, Phil made his prediction.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2012, 1, 'Six More Weeks of Winter The skies slightly overcast and a temperate of 30°. Phil saw his shadow!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2013, 0, 'No Shadow- Early Spring A Balmy 7° Phil made his prediction at 7:25 a.m.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2014, 1, 'Six More Weeks of Winter With fog in site, Phil made his prediction at 7:26 a.m.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2015, 1, 'Six More Weeks of Winter Was the prediction of Phil. The morning was filled with freezing rain. Phil emerged from his burrow at 7:26 a.m.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2016, 0, 'No Shadow- Early Spring It was 28° at Gobbler’s Knob. Phil made his perdition of an Early Spring at 7:25 a.m.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2017, 1, '7:25 a.m. Saw His Shadow, Six More Weeks of Winter! There were a few snow flurries during the prognostication.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2018, 1, 'At 7:25 a.m. with 18,000 Phil Phans present, Phil saw his shadow! Six More Weeks of Winter!');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2019, 0, 'NO Shadow at 7:28 AM; 14º fog & mist with -1º Wind Chill.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2020, 0, 'NO Shadow at 7:26 AM; 30º with light snow falling.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2021, 1, 'Shadow at 7:25 AM; 19º with light snow. Coronavirus fear prohibits crowds on Gobbler’s Knob.');
INSERT INTO predictions (slug, year, shadow, details) VALUES ('punxsutawney-phil', 2022, 1, 'Shadow at 7:27 AM; 27º with clear skies. A loyal crowd of thousands returned to Gobbler’s Knob.');

-- Down
DROP TABLE IF EXISTS predictions;
DROP TABLE IF EXISTS groundhogs;
